# Generated by Django 5.0.2 on 2024-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
