# Generated by Django 5.0.2 on 2024-05-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
