# Generated by Django 5.0.2 on 2024-05-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_kullanici'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
