# Generated by Django 5.0.2 on 2024-05-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_category_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Kullanici',
        ),
    ]
