# Generated by Django 5.0.2 on 2024-06-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_kullanici_groups_kullanici_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanici',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='kullanici',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='skincarepro',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
