# Generated by Django 5.0.2 on 2024-06-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_kullanici_groups_remove_kullanici_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orderd',
            new_name='date_ordered',
        ),
    ]
