# Generated by Django 5.0.2 on 2024-06-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_date_orderd_order_date_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date_orderd',
        ),
    ]
