# Generated by Django 5.0.2 on 2024-06-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
