# Generated by Django 5.0.2 on 2024-06-05 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_type',
            field=models.CharField(choices=[('product', 'Product'), ('skincarepro', 'Skincarepro')], default='product', max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='skincarepro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.skincarepro'),
        ),
    ]
