# Generated by Django 5.0.2 on 2024-06-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_product_weight_orderitem_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='skincarepro',
        ),
    ]
